{
 "title": "GNO staking dashboard lot keys for lighthouse",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "node_job", "query": "lighthouse" },
   { "name": "validator_job", "query": "lighthouse_validator" },
   {
    "name": "fiat",
    "label": "Currency converter",
    "query": {
     "query": "label_values(crypto_currency, pair)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Validators statuses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(validator_monitor_active) or on() vector(0)",
     "legendFormat": "Total"
    },
    {
     "expr": "count(validator_monitor_active==1) or on() vector(0)",
     "legendFormat": "Active"
    },
    {
     "expr": "count(validator_monitor_active==0) or on() vector(0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "count(validator_statuses==1) or on() vector(0)",
     "legendFormat": "Deposited"
    },
    {
     "expr": "count(validator_monitor_slashed==1) or on() vector(0)",
     "legendFormat": "Slashing"
    },
    {
     "expr": "count(validator_monitor_exited==1) or on() vector(0)",
     "legendFormat": "Exiting"
    },
    {
     "expr": "count(validator_statuses==6) or on() vector(0)",
     "legendFormat": "Exited"
    },
    {
     "expr": "count(validator_statuses==0) or on() vector(0)",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Hourly earning",
   "type": "stat",
   "description": "This panel shows the earning during the last hour, and the annualized % of the hourly earning.\n\nThose data won't be shown until the first validator is at least one hour old, or that you started Prometheus at least one hour ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_monitor_balance_gwei) - sum(validator_monitor_balance_gwei offset 1h) - count(validator_monitor_balance_gwei > 16)*32 + count(validator_monitor_balance_gwei offset 1h > 0)*32)*absent(crypto_currency{pair=~\"mGNO$fiat\"})/1000000000",
     "legendFormat": "mGNO"
    },
    {
     "expr": "(sum(validator_monitor_balance_gwei) - sum(validator_monitor_balance_gwei offset 1h) - count(validator_monitor_balance_gwei > 16)*32 + count(validator_monitor_balance_gwei offset 1h > 0)*32)*sum(crypto_currency{pair=\"mGNO$fiat\"})/1000000000",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_monitor_balance_gwei) - sum(validator_monitor_balance_gwei offset 1h) - count(validator_monitor_balance_gwei > 16)*32 + count(validator_monitor_balance_gwei offset 1h > 0)*32)/(avg_over_time(count(validator_monitor_balance_gwei > 16)[1h:30s])*32/24/365)*100/1000000000",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Daily earning",
   "type": "stat",
   "description": "This panel shows the earning during the last day, and the annualized % of the daily earning.\n\nThose data won't be shown until the first validator is at least one day old, or that you started Prometheus at least one day ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_monitor_balance_gwei) - sum(validator_monitor_balance_gwei offset 1d) - count(validator_monitor_balance_gwei > 16)*32 + count(validator_monitor_balance_gwei offset 1d > 0)*32)*absent(crypto_currency{pair=~\"mGNO$fiat\"})/32/1000000000",
     "legendFormat": "GNO"
    },
    {
     "expr": "(sum(validator_monitor_balance_gwei) - sum(validator_monitor_balance_gwei offset 1d) - count(validator_monitor_balance_gwei > 16)*32 + count(validator_monitor_balance_gwei offset 1d > 0)*32)*sum(crypto_currency{pair=\"mGNO$fiat\"})/1000000000",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_monitor_balance_gwei) - sum(validator_monitor_balance_gwei offset 1d) - count(validator_monitor_balance_gwei > 16)*32 + count(validator_monitor_balance_gwei offset 1d > 0)*32)/(avg_over_time(count(validator_monitor_balance_gwei > 16)[1d:12m])*32/365)*100/1000000000",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Weekly earning",
   "type": "stat",
   "description": "This panel shows the earning during the last week, and the annualized % of the weekly earning.\n\nThose data won't be shown until the first validator is at least one week old, or that you started Prometheus at least one week ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_monitor_balance_gwei) - sum(validator_monitor_balance_gwei offset 1w) - count(validator_monitor_balance_gwei > 16)*32 + count(validator_monitor_balance_gwei offset 1w > 0)*32)*absent(crypto_currency{pair=~\"mGNO$fiat\"})/32/1000000000",
     "legendFormat": "GNO"
    },
    {
     "expr": "(sum(validator_monitor_balance_gwei) - sum(validator_monitor_balance_gwei offset 1w) - count(validator_monitor_balance_gwei > 16)*32 + count(validator_monitor_balance_gwei offset 1w > 0)*32)*sum(crypto_currency{pair=\"mGNO$fiat\"})/1000000000",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_monitor_balance_gwei) - sum(validator_monitor_balance_gwei offset 1w) - count(validator_monitor_balance_gwei > 16)*32 + count(validator_monitor_balance_gwei offset 1w > 0)*32)/(avg_over_time(count(validator_monitor_balance_gwei > 16)[1w:84m])*32*7/365)*100/1000000000",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Monthly earning",
   "type": "stat",
   "description": "This panel shows the earning during the last month, and the annualized % of the monthly earning.\n\nThose data won't be shown until the first validator is at least one month old, or that you started Prometheus at least one month ago. Ensure to run Prometheus with the flag `--storage.tsdb.retention.time=31d` if you want this panel to get enough data\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_monitor_balance_gwei) - sum(validator_monitor_balance_gwei offset 30d) - count(validator_monitor_balance_gwei > 16)*32 + count(validator_monitor_balance_gwei offset 30d > 0)*32)*absent(crypto_currency{pair=~\"mGNO$fiat\"})/32/1000000000",
     "legendFormat": "GNO"
    },
    {
     "expr": "(sum(validator_monitor_balance_gwei) - sum(validator_monitor_balance_gwei offset 30d) - count(validator_monitor_balance_gwei > 16)*32 + count(validator_monitor_balance_gwei offset 30d > 0)*32)*sum(crypto_currency{pair=\"mGNO$fiat\"})/1000000000",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_monitor_balance_gwei) - sum(validator_monitor_balance_gwei offset 30d) - count(validator_monitor_balance_gwei > 16)*32 + count(validator_monitor_balance_gwei offset 30d > 0)*32)/(avg_over_time(count(validator_monitor_balance_gwei > 16)[30d:6h])*32/12)*100/1000000000",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Total earning",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_monitor_balance_gwei) - count(validator_monitor_balance_gwei > 16 and validator_monitor_active == 1)*32*absent(crypto_currency{pair=~\"GNO$fiat\"}))/32/1000000000",
     "legendFormat": "GNO"
    },
    {
     "expr": "(sum(validator_monitor_balance_gwei) - count(validator_monitor_balance_gwei > 16 and validator_monitor_active == 1)*32)*sum(crypto_currency{pair=\"GNO$fiat\"})/1000000000",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_monitor_balance_gwei) - count(validator_monitor_balance_gwei > 16E9 and validator_monitor_active == 1)*32E9)*100/(count(validator_monitor_balance_gwei > 16E9 and validator_monitor_active == 1)*32E9)",
     "legendFormat": "ROI"
    }
   ]
  },
  {
   "title": "Process Started",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{instance=\"consensus-client:5054\"})/3600",
     "legendFormat": "Beacon"
    },
    {
     "expr": "(time()-process_start_time_seconds{instance=\"validator-client:5056\"})/3600",
     "legendFormat": "Validator"
    }
   ]
  },
  {
   "title": "Total balance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(validator_monitor_balance_gwei > 16)/32)/1000000000",
     "legendFormat": "Total balance"
    }
   ]
  },
  {
   "title": "Validator balance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(validator_monitor_balance_gwei>16)-32",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Hardware usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(process_resident_memory_bytes{job=\"$node_job\"}[1m:5s])",
     "legendFormat": "memory {{job}}"
    },
    {
     "expr": "avg_over_time(process_resident_memory_bytes{job=\"$validator_job\"}[1m:5s])",
     "legendFormat": "memory {{job}}"
    },
    { "expr": "system_loadavg_1", "legendFormat": "load avg {{job}}" }
   ]
  },
  {
   "title": "Validator vote summary",
   "type": "table",
   "description": "This panel will count only the votes done since your validator process started",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "max by (validator) (validator_monitor_unaggregated_attestation_total)"
    },
    {
     "expr": "max by (validator) (validator_monitor_aggregated_attestation_total)"
    },
    {
     "expr": "max by (validator) (validator_monitor_beacon_block_total)"
    }
   ]
  },
  {
   "title": "Validator main info",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "max by(validator) (validator_monitor_balance_gwei/1E9)"
    },
    {
     "expr": "max by(validator) (validator_monitor_active)",
     "legendFormat": "Active"
    },
    {
     "expr": "max by(validator) (validator_monitor_slashed*1000)",
     "legendFormat": "Slashed"
    },
    {
     "expr": "max by(validator) (validator_monitor_exited*10)",
     "legendFormat": "Exited"
    },
    {
     "expr": "max by(validator) (validator_monitor_withdrawable*100)",
     "legendFormat": "Withdrawable"
    },
    {
     "expr": "validator_monitor_validator_in_current_sync_committee{}",
     "legendFormat": "Sync Committee"
    }
   ]
  },
  {
   "title": "Hourly earning mGNO last 24 hours",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(validator_monitor_balance_gwei) - sum(validator_monitor_balance_gwei offset 1h))/1000000000 >= 0",
     "legendFormat": "Hourly earning"
    },
    {
     "expr": "(sum(validator_monitor_balance_gwei) - sum(validator_monitor_balance_gwei offset 1h))/1000000000 <= 0",
     "legendFormat": "Hourly loosing"
    }
   ]
  },
  {
   "title": "Daily earning GNO last 7 days",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(validator_monitor_balance_gwei) - sum(validator_monitor_balance_gwei offset 1d))/32/1000000000 >= 0",
     "legendFormat": "Daily earning"
    },
    {
     "expr": "(sum(validator_monitor_balance_gwei) - sum(validator_monitor_balance_gwei offset 1d))/32/1000000000 < 0",
     "legendFormat": "Daily loosing"
    }
   ]
  },
  {
   "title": "NODE",
   "type": "stat",
   "gridPos": { "h": 1, "w": 13, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "NODE" }
   ]
  },
  {
   "title": "Node process started",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{instance=\"consensus-client:5054\"})/3600"
    }
   ]
  },
  {
   "title": "Warn: The process just restarted",
   "type": "timeseries",
   "description": "This alert is useful only for people who has automatic restart of the process after crash. \nThis can be made for example by using the prysm.bat file on windows with \"set PRYSM_AUTORESTART=true&\", or with docker with \"--restart always\"",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{instance=\"consensus-client:5054\"})/3600",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "(time()-process_start_time_seconds{instance=\"validator-client:5056\"})/3600",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Alert: 50 errors  or 100 warns  in 1h",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "error_total{instance=\"consensus-client:5054\"} - error_total{instance=\"consensus-client:5054\"} offset 1h",
     "legendFormat": "errors"
    },
    {
     "expr": "warn_total{instance=\"consensus-client:5054\"} - warn_total{instance=\"consensus-client:5054\"} offset 1h",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Balance validators status and participation rate",
   "type": "timeseries",
   "description": "This graph is made for trading purpose mostly.\nSupposing that if a lot of validators are exiting, price is gonna dump.\n\nYoldark : Not working as supposed right now because lighthouse do not provide enough information on the state of the network\n\nAlso this can prevent to exit while exiting queue is too long, same for depositing while pending queue is too long.\n\n",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "beacon_head_state_validator_balances_total / 1E9"
    },
    {
     "expr": "(beacon_participation_prev_epoch_head_attesting_gwei_total/beacon_participation_prev_epoch_target_attesting_gwei_total)*100",
     "legendFormat": "Participation rate"
    }
   ]
  },
  {
   "title": "Slots behind",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slotclock_present_slot-beacon_head_state_latest_block_slot",
     "legendFormat": "Slots behind"
    }
   ]
  },
  {
   "title": "Hourly log type counter",
   "type": "bargauge",
   "description": "This panel won't have consistant values during the first hour of the node started process",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "error_total{instance=\"consensus-client:5054\"} - error_total{instance=\"consensus-client:5054\"} offset 1h",
     "legendFormat": "Errors"
    },
    {
     "expr": "warn_total{instance=\"consensus-client:5054\"} - warn_total{instance=\"consensus-client:5054\"} offset 1h",
     "legendFormat": "Warns"
    }
   ]
  },
  {
   "title": "Alert: Process down",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{instance=\"consensus-client:5054\"}",
     "legendFormat": "beacon node"
    },
    {
     "expr": "up{instance=\"validator-client:5056\"}",
     "legendFormat": "validator"
    }
   ]
  },
  {
   "title": "Alert: 50 slots behind",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "beacon_head_state_latest_block_slot-beacon_head_state_slot",
     "legendFormat": "node slots behind"
    }
   ]
  },
  {
   "title": "Peers connected",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "libp2p_peers" }
   ]
  },
  {
   "title": "Alert: Participation rate < 66%",
   "type": "timeseries",
   "description": "I'm not sure about this one yet",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(beacon_participation_prev_epoch_head_attesting_gwei_total/beacon_participation_prev_epoch_target_attesting_gwei_total)*100"
    }
   ]
  },
  {
   "title": "ALERTS",
   "type": "stat",
   "gridPos": { "h": 1, "w": 7, "x": 9, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Alert : Validator loosing money",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(validator_monitor_balance_gwei[840s])"
    }
   ]
  },
  { "title": "All alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 7, "x": 9, "y": 37 } },
  {
   "title": "Alert: Hourly earning <= 0",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(validator_monitor_balance_gwei) - sum(validator_monitor_balance_gwei offset 1h) - count(validator_monitor_balance_gwei > 16E9)*32E9 + count(validator_monitor_balance_gwei offset 1h > 0)*32E9",
     "legendFormat": "validators earning on 1h"
    }
   ]
  },
  {
   "title": "Alert: Validator has been slashed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "validator_monitor_slashed", "legendFormat": "{{validator}}" }
   ]
  }
 ]
}