{
 "title": "Validator Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Lighthouse Validator Monitor\n\nMetrics collected from a Lighthouse Beacon Node.\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Monitored Validators Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "validator_monitor_validators_total"
    }
   ]
  },
  {
   "title": "Active Validators",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(validator_monitor_active)" }
   ]
  },
  {
   "title": "Slashed Validators",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(validator_monitor_slashed)" }
   ]
  },
  {
   "title": "Validator Balance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "validator_monitor_balance_gwei" }
   ]
  },
  {
   "title": "Exited Validators",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(validator_monitor_exited)" }
   ]
  },
  {
   "title": "Withdrawable Validators",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_withdrawable)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "options": {
    "content": "\n## Summary of Events in the Previous Epoch\n\nContains the summary of validator events in the previous epoch. These figures can be used to monitor the performance and online-ness of specific validators.\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Prev Epoch Attestation included in Block",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_attestation_block_inclusions"
    }
   ]
  },
  {
   "title": "Prev Epoch Unagg Attestations Seen",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_attestations_total"
    }
   ]
  },
  {
   "title": "Prev Epoch Aggregate Attestations Seen",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_aggregates_total"
    }
   ]
  },
  {
   "title": "Prev Epoch Blocks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_beacon_blocks_total"
    }
   ]
  },
  {
   "title": "Prev Epoch Attestation included in Aggregate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_attestation_aggregate_inclusions"
    }
   ]
  },
  {
   "title": "Prev Epoch Voluntary Exits Seen",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none", "label": "VoluntaryExit" }
   ],
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_exits_total"
    }
   ]
  },
  {
   "title": "Prev Epoch Proposer Slashing Seen",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "none", "label": "ProposerSlashing" }
   ],
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_proposer_slashings_total"
    }
   ]
  },
  {
   "title": "Prev Epoch Attester Slashing Seen",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "none", "label": "AttesterSlashing" }
   ],
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_attester_slashings_total"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "\n## Minimum Message Delays in the Previous Epoch\n\nThese are the delays between when a message was due and when we recieved it. The values displayed here are the minimum delays per validator.\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Prev Epoch Min Attestation Inclusion Delay (Slots)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Slots" }
   ],
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_attestation_block_min_inclusion_distance"
    }
   ]
  },
  {
   "title": "Prev Epoch Min Unagg. Attestation Delay",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(validator_monitor_prev_epoch_attestations_min_delay_seconds_sum[30s])\n/\nrate(validator_monitor_prev_epoch_attestations_min_delay_seconds_count[30s])"
    }
   ]
  },
  {
   "title": "Prev Epoch Min Block Delay",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(validator_monitor_prev_epoch_beacon_blocks_min_delay_seconds_sum[30s])\n/\nrate(validator_monitor_prev_epoch_beacon_blocks_min_delay_seconds_count[30s])"
    }
   ]
  },
  {
   "title": "Prev Epoch Min Aggregate Attestation Delay",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(validator_monitor_prev_epoch_aggregates_min_delay_seconds_sum[30s])\n/\nrate(validator_monitor_prev_epoch_aggregates_min_delay_second_count[30s])"
    }
   ]
  },
  {
   "title": "Attestation Inclusion in a Block per Minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "none", "label": "Block Inclusions" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_attestation_in_block_total[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 44 },
   "options": {
    "content": "\n## Real-Time Validator Events\n\nDisplays events happening per validator in real-time.\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Attestation inclusion in Block per Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none", "label": "Block Inclusions" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_attestation_in_block_total[1m])"
    }
   ]
  },
  {
   "title": "Unaggregated Attestations Seen per Minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 47 },
   "yaxes": [
    { "format": "none", "label": "Attestation" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_unaggregated_attestation_total[1m])"
    }
   ]
  },
  {
   "title": "Aggregated Attestations Seen per Minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "none", "label": "SignedAggregateAndProof" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_aggregated_attestation_total[1m])"
    }
   ]
  },
  {
   "title": "Beacon Blocks Seen per Minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 52 },
   "yaxes": [
    { "format": "none", "label": "BeaconBlock" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_beacon_block_total[1m])"
    }
   ]
  },
  {
   "title": "Attestation inclusion in Aggregate per Minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "none", "label": "Aggregate Inclusions" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_attestation_in_aggregate_total[1m])"
    }
   ]
  },
  {
   "title": "Voluntary Exits Seen per Minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none", "label": "VoluntaryExit" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_exit_total[1m])"
    }
   ]
  },
  {
   "title": "Proposer Slashing Seen per Minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "none", "label": "ProposerSlashing" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_proposer_slashing_total[1m])"
    }
   ]
  },
  {
   "title": "Attester Slashing Seen per Minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "none", "label": "AttesterSlashing" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_attester_slashing_total[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 62 },
   "options": {
    "content": "\n## Real-Time Validator Message Delays\n\nDisplays message delays per validator in real-time.\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Attestation Inclusion Delay (Slots)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short", "label": "Slots" }
   ],
   "targets": [
    {
     "expr": "validator_monitor_attestation_in_block_delay_slots"
    }
   ]
  },
  {
   "title": "Unaggregated Attestation Delay Times",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 65 },
   "targets": [
    {
     "expr": "rate(validator_monitor_unaggregated_attestation_delay_seconds_sum[30s])\n/\nrate(validator_monitor_unaggregated_attestation_delay_seconds_count[30s])"
    }
   ]
  },
  {
   "title": "Beacon Block Delay Times",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 65 },
   "targets": [
    {
     "expr": "rate(validator_monitor_beacon_block_delay_seconds_sum[30s])\n/\nrate(validator_monitor_beacon_block_delay_seconds_count[30s])"
    }
   ]
  },
  {
   "title": "Aggregated Attestation Delay Times",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 70 },
   "targets": [
    {
     "expr": "rate(validator_monitor_aggregated_attestation_delay_seconds_sum[30s])\n/\nrate(validator_monitor_aggregated_attestation_delay_seconds_count[30s])"
    }
   ]
  },
  {
   "title": "Inclusion in Attestation Delay",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 70 },
   "targets": [
    {
     "expr": "rate(validator_monitor_attestation_in_aggregate_delay_seconds_sum[30s])\n/\nrate(validator_monitor_attestation_in_aggregate_delay_seconds_count[30s])"
    }
   ]
  }
 ]
}