{
 "title": "Node Stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Host Metrics\n\nDisplays information about the testnet host machines\n\nMetrics collected using [prometheus/node_exporter](https://github.com/prometheus/node_exporter)\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Load (loadavg 1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "\n### Memory (RAM) Utilization\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Used (Total Memory - Available Memory)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "options": { "content": "\n### Network Utilization\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Bytes Tx (eth0) 1m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_transmit_bytes_total{device=\"eth0\"}[1m])"
    }
   ]
  },
  {
   "title": "Network Bytes Rx (eth0) 1m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{device=\"eth0\"}[1m])"
    }
   ]
  },
  {
   "title": "Socketstat TCP Alloc",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_sockstat_TCP_alloc" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 33 },
   "options": { "content": "\n### Disk Utilization\n" },
   "content": "\n### Disk Utilization\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "Filesystem Free Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/xvda1\"}"
    }
   ]
  }
 ]
}